# Define rings
MAX_NUM_RINGS = 0

# Define goals
MAX_NUM_RED_GOALS = 2
MAX_NUM_BLUE_GOALS = 2
MAX_NUM_LOW_NEUTRAL_GOALS = 2
MAX_NUM_HIGH_NEUTRAL_GOALS = 1

# Define robots
MAX_NUM_HOST_ROBOTS = 1
MAX_NUM_PARTNER_ROBOTS = 1
MAX_NUM_OPPOSING_ROBOTS = 2

# Define ramp size
PLATFORM_LENGTH_IN = 50
PLATFORM_WIDTH_IN = 24
FIELD_WIDTH_IN = 144

# Define figure size
FIG_SIZE = (12, 12)